// Generated by scripts/build-section-art.mjs (npm run art:sections). Do not edit by hand.
// What is in public/art/sections/: sizes are art pixels, sequences are [frame, milliseconds] steps.
export const sectionArt = {
  "thumb": {
    "w": 112,
    "h": 70
  },
  "tiles": {
    "edge": {
      "depth": 4,
      "top": 64,
      "right": 40,
      "bottom": 56,
      "left": 48
    },
    "seam": {
      "w": 160,
      "h": 28
    },
    "jali": {
      "w": 12,
      "h": 12
    },
    "star": {
      "w": 11,
      "h": 11
    },
    "spark": {
      "w": 7,
      "h": 7
    },
    "arch": {
      "w": 20,
      "h": 20
    },
    "kilim": {
      "w": 16,
      "h": 11
    },
    "grain": {
      "w": 64,
      "h": 64
    },
    "stars": [211, 307]
  },
  "creative": {
    "band": {
      "src": "creative/band.png",
      "w": 352,
      "h": 198,
      "focus": [236, 116],
      "glints": [[196, 152], [234, 150], [255, 154], [221, 157], [211, 136]],
      "sparkles": [[225, 141], [228, 143], [223, 144], [227, 139]],
      "windows": []
    },
    "sprites": {
      "lantern": {
        "src": "creative/lantern.png",
        "w": 14,
        "h": 47,
        "frames": 3,
        "at": [69, 30],
        "sequences": {
          "idle": [[0, 800], [1, 800], [0, 800], [2, 800]]
        }
      },
      "parrot": {
        "src": "creative/parrot.png",
        "w": 17,
        "h": 30,
        "frames": 3,
        "at": [96, 123],
        "sequences": {
          "idle": [
            [0, 2100],
            [1, 130],
            [0, 1200],
            [2, 1500],
            [0, 400],
            [1, 130],
            [0, 1700],
            [2, 300],
            [0, 300],
            [2, 900]
          ]
        }
      },
      "cat": {
        "src": "creative/cat.png",
        "w": 24,
        "h": 30,
        "frames": 3,
        "at": [9, 139],
        "sequences": {
          "idle": [[0, 1800], [1, 1800], [0, 1800], [1, 1200], [2, 150], [1, 450]]
        }
      },
      "tray": {
        "src": "creative/tray.png",
        "w": 35,
        "h": 24,
        "frames": 4,
        "at": [100, 153],
        "sequences": {
          "idle": [[0, 420], [1, 420], [2, 420], [3, 420]]
        }
      },
      "table": {
        "src": "creative/table.png",
        "w": 28,
        "h": 41,
        "frames": 1,
        "at": [127, 124],
        "sequences": {
          "idle": [[0, 1000]]
        }
      },
      "figure": {
        "src": "creative/figure.png",
        "w": 57,
        "h": 61,
        "frames": 3,
        "at": [46, 101],
        "sequences": {
          "idle": [
            [0, 1100],
            [1, 170],
            [0, 170],
            [1, 170],
            [0, 600],
            [2, 240],
            [0, 1700],
            [1, 200],
            [2, 200],
            [0, 900]
          ]
        }
      },
      "kite": {
        "src": "creative/kite.png",
        "w": 9,
        "h": 12,
        "frames": 3,
        "at": [309, 89],
        "sequences": {
          "idle": [[0, 520], [1, 520], [2, 520], [1, 520]]
        }
      },
      "kite-blue": {
        "src": "creative/kite-blue.png",
        "w": 9,
        "h": 12,
        "frames": 3,
        "at": [334, 90],
        "sequences": {
          "idle": [[0, 520], [1, 520], [2, 520], [1, 520]]
        }
      },
      "cypress": {
        "src": "creative/cypress.png",
        "w": 16,
        "h": 52,
        "frames": 2,
        "at": [152, 68],
        "sequences": {
          "idle": [[0, 2600], [1, 1400]]
        }
      }
    },
    "thumbs": ["pavilion", "pool", "horizon", "canopy", "beds", "lantern", "carpet", "sky", "cypress", "cat"]
  },
  "tech": {
    "band": {
      "src": "tech/band.png",
      "w": 352,
      "h": 198,
      "focus": [236, 112],
      "glints": [[196, 152], [236, 151], [256, 155], [224, 157], [212, 138]],
      "sparkles": [[225, 141], [228, 143], [223, 144]],
      "windows": [
        [76, 94, "#5b2831"],
        [109, 94, "#5b2831"],
        [143, 95, "#584f24"],
        [335, 100, "#5b2831"],
        [272, 101, "#573c63"],
        [303, 102, "#5b2831"],
        [320, 102, "#5b2831"]
      ]
    },
    "sprites": {
      "lantern": {
        "src": "tech/lantern.png",
        "w": 15,
        "h": 49,
        "frames": 5,
        "at": [69, 30],
        "sequences": {
          "idle": [
            [0, 420],
            [2, 120],
            [0, 260],
            [1, 90],
            [0, 330],
            [3, 300],
            [2, 110],
            [3, 290],
            [0, 400],
            [1, 100],
            [2, 140],
            [0, 310],
            [4, 330],
            [1, 90],
            [4, 280]
          ]
        }
      },
      "cat": {
        "src": "tech/cat.png",
        "w": 27,
        "h": 21,
        "frames": 2,
        "at": [9, 148],
        "sequences": {
          "idle": [[0, 2000], [1, 2000]]
        }
      },
      "rover": {
        "src": "tech/rover.png",
        "w": 20,
        "h": 19,
        "frames": 4,
        "at": [152, 156],
        "sequences": {
          "idle": [[0, 1100], [1, 500]],
          "drive": [[0, 260], [2, 260], [0, 260], [2, 260], [1, 260], [3, 260]]
        }
      },
      "tray": {
        "src": "tech/tray.png",
        "w": 35,
        "h": 18,
        "frames": 1,
        "at": [80, 164],
        "sequences": {
          "idle": [[0, 1000]]
        }
      },
      "table": {
        "src": "tech/table.png",
        "w": 30,
        "h": 41,
        "frames": 1,
        "at": [126, 124],
        "sequences": {
          "idle": [[0, 1000]]
        }
      },
      "figure": {
        "src": "tech/figure.png",
        "w": 73,
        "h": 53,
        "frames": 4,
        "at": [48, 111],
        "sequences": {
          "idle": [
            [1, 120],
            [0, 120],
            [1, 120],
            [0, 120],
            [1, 120],
            [0, 360],
            [1, 120],
            [0, 120],
            [1, 120],
            [0, 480],
            [2, 360],
            [3, 120],
            [2, 120],
            [3, 120],
            [2, 120],
            [3, 120],
            [2, 120],
            [3, 120],
            [2, 600]
          ]
        }
      },
      "cypress": {
        "src": "tech/cypress.png",
        "w": 16,
        "h": 52,
        "frames": 2,
        "at": [152, 68],
        "sequences": {
          "idle": [[0, 2600], [1, 1400]]
        }
      }
    },
    "thumbs": ["pavilion", "pool", "horizon", "canopy", "beds", "lantern", "carpet", "sky", "cypress", "cat"]
  }
} as const;
